server:
  port: ${APP_PORT}

spring:
  application:
    name: chapchap-gateway
  web:
    error:
      include-stacktrace: always
      include-message: always
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestSize
              args:
                maxSize: 20MB
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: ${CORS_ALLOW_ORIGIN}
                allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
                allowed-headers: "*"
                allow-credentials: true
          routes:
              # Auth-Service
            - id: ${AUTH_SERVICE_NAME}
              uri: ${AUTH_SERVICE_URI}
              predicates:
                - Path=${AUTH_SERVICE_PREDICATE}
              # Auth-Service Open API
            - id: ${AUTH_SERVICE_NAME}-docs
              uri: ${AUTH_SERVICE_URI}
              predicates:
                - Path=/${AUTH_SERVICE_NAME}${AUTH_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${AUTH_SERVICE_NAME}${AUTH_SERVICE_OPEN_API_PATH}, ${AUTH_SERVICE_OPEN_API_PATH}

              # Product-Service
            - id: ${PRODUCT_SERVICE_NAME}
              uri: ${PRODUCT_SERVICE_URI}
              predicates:
                - Path=${PRODUCT_SERVICE_PREDICATE}
              # Product-Service Open API
            - id: ${PRODUCT_SERVICE_NAME}-docs
              uri: ${PRODUCT_SERVICE_URI}
              predicates:
                - Path=/${PRODUCT_SERVICE_NAME}${PRODUCT_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${PRODUCT_SERVICE_NAME}${PRODUCT_SERVICE_OPEN_API_PATH}, ${PRODUCT_SERVICE_OPEN_API_PATH}

              # Subscription-Service
            - id: ${SUBSCRIPTION_SERVICE_NAME}
              uri: ${SUBSCRIPTION_SERVICE_URI}
              predicates:
                - Path=${SUBSCRIPTION_SERVICE_PREDICATE}
              # Subscription-Service Open API
            - id: ${SUBSCRIPTION_SERVICE_NAME}-docs
              uri: ${SUBSCRIPTION_SERVICE_URI}
              predicates:
                - Path=/${SUBSCRIPTION_SERVICE_NAME}${SUBSCRIPTION_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${SUBSCRIPTION_SERVICE_NAME}${SUBSCRIPTION_SERVICE_OPEN_API_PATH}, ${SUBSCRIPTION_SERVICE_OPEN_API_PATH}

              # Delivery-Service
            - id: ${DELIVERY_SERVICE_NAME}
              uri: ${DELIVERY_SERVICE_URI}
              predicates:
                - Path=${DELIVERY_SERVICE_PREDICATE}
              # Delivery-Service Open API
            - id: ${DELIVERY_SERVICE_NAME}-docs
              uri: ${DELIVERY_SERVICE_URI}
              predicates:
                - Path=/${DELIVERY_SERVICE_NAME}${DELIVERY_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${DELIVERY_SERVICE_NAME}${DELIVERY_SERVICE_OPEN_API_PATH}, ${DELIVERY_SERVICE_OPEN_API_PATH}

              # Customer-Service
            - id: ${CUSTOMER_SERVICE_NAME}
              uri: ${CUSTOMER_SERVICE_URI}
              predicates:
                - Path=${CUSTOMER_SERVICE_PREDICATE}
              # Customer-Service Open API
            - id: ${CUSTOMER_SERVICE_NAME}-docs
              uri: ${CUSTOMER_SERVICE_URI}
              predicates:
                - Path=/${CUSTOMER_SERVICE_NAME}${CUSTOMER_SERVICE_OPEN_API_PATH}
              filters:
                - RewritePath=/${CUSTOMER_SERVICE_NAME}${CUSTOMER_SERVICE_OPEN_API_PATH}, ${CUSTOMER_SERVICE_OPEN_API_PATH}

# OPEN API
springdoc:
  swagger-ui:
    path: /docs
    urls:
        # Auth-Service Open API Doc Url
      - name: ${AUTH_SERVICE_NAME}
        url: /${AUTH_SERVICE_NAME}${AUTH_SERVICE_OPEN_API_PATH}
        # Product-Service Open API Doc Url
      - name: ${PRODUCT_SERVICE_NAME}
        url: /${PRODUCT_SERVICE_NAME}${PRODUCT_SERVICE_OPEN_API_PATH}
        # Subscription-Service Open API Doc Url
      - name: ${SUBSCRIPTION_SERVICE_NAME}
        url: /${SUBSCRIPTION_SERVICE_NAME}${SUBSCRIPTION_SERVICE_OPEN_API_PATH}
        # Delivery-Service Open API Doc Url
      - name: ${DELIVERY_SERVICE_NAME}
        url: /${DELIVERY_SERVICE_NAME}${DELIVERY_SERVICE_OPEN_API_PATH}
        # Customer-Service Open API Doc Url
      - name: ${CUSTOMER_SERVICE_NAME}
        url: /${CUSTOMER_SERVICE_NAME}${CUSTOMER_SERVICE_OPEN_API_PATH}

jwt:
  secret: ${JWT_SECRET}
  header-key: Authorization
  scheme: Bearer

